### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by PavelVanecek** [mustford/ionPlantApp#1]
Hi mustford! Can you add a brief README please?

**Comment by mustford** [comment]
Hello, Pavel!
I've added some description. If you need any more info, please, ask me.

**Comment by PavelVanecek** [comment]
Thanks! Can you please also add instructions how to run the app on a device?

**Comment by mustford** [comment]
By the matter of fact this app is under development and is not tested on different devices(only on mine android 4.1) and is far from intended functionality and design. You can check it out in browser, but in this case you can't upload photo from the gallery of mobile and so can't get recognition of image. For testing on android virtual device you need android studio and sdk. For testing on mobile just build .apk file and upload on device.

**Comment by PavelVanecek** [comment]
Great now. Thank you!
